Fix issues in Part 4
dotnet-presentations/dotnet-maui-workshop pull request #59
Opened 2022-05-26 14:54 UTC by khalidabuhakmeh

- Readme code using incorrect properties and API methods.
- XAML end tag in MainPage.xaml was incorrect.
- Shorter LINQ Query using MinBy

2022-05-26 14:57 UTC, khalidabuhakmeh commented
This is kind of related but noticed the details page looks off for me.

<img width="458" alt="Screenshot 2022-05-26 at 10 50 48" src="https://user-images.githubusercontent.com/228256/170514990-04ededae-03f6-4c4a-a266-aea88d6a344b.png">

2022-05-26 17:03 UTC, jamesmontemagno approved these changes

2022-05-27 06:31 UTC, jamesmontemagno commented on Part 4 - Platform Features/README.md
> +    builder.Services.AddSingleton<IMap>(Map.Current);
They are both .Default for me..  https://github.com/dotnet/maui/blob/main/src/Essentials/src/Geolocation/Geolocation.shared.cs#L37

Current is private

2022-05-27 06:32 UTC, jamesmontemagno commented on Part 4 - Platform Features/README.md
> -            await map.OpenAsync(Monkey.Latitude, Monkey.Longitude, new MapLaunchOptions
This api was changed back. Make sure you are compiling against the latest GA build

2022-05-27 06:34 UTC, jamesmontemagno requested changes
Jon fixed up the mainpage.xaml... for the other stuff bysides minby would need to be reverted and then updated in the source code for 5, 6, and final

2022-05-27 14:55 UTC, closed without merging

2022-05-27 15:09 UTC, khalidabuhakmeh commented
I'm running `sudo dotnet workload update` but the CLI only ever finds the `RC1` bits. 😢